# FROM node:18-slim
FROM node:18-alpine3.16

# USER root
# RUN apt-get install -y git

WORKDIR /work
# WORKDIR /home/node/zenn
# USER node

RUN npm init --yes && npm install zenn-cli
    # apt-get update && \
    # apt-get install -y git && \
    

# VOLUME [ "/data" ]