# FROM node:18-slim
FROM node:18-alpine3.16

# RUN apt-get install -y git

WORKDIR /work
# WORKDIR /home/node/zenn
# USER node

RUN npm install zenn-cli@latest
    # apt-get update && \
    # apt-get install -y git && \
    

# VOLUME [ "/data" ]
